# Generated by Django 5.1.4 on 2025-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0003_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                related_name="orders", to="cafe.item", verbose_name="orders"
            ),
        ),
    ]
